### ISSUE TITLE
Exclamation point not a valid start character any longer

### ISSUE THREAD

**Issue by SublimeNemesis** [mrrosh/FollowMeEnhanced#2]
The exclamation point (!) causes the server to expect a server command. As !follow is not a valid server command, trying to use the add on causes the game to return the error "There is no such command".

To fix this, change the exclamation point in FollowMeEnhanced.lua and localization.lua to a different symbol. I was able to get the add on to work when I changed the ! to an @.

**Comment by mrrosh** [comment]
Thanks, fixed.
